### ISSUE TITLE
a problem with adds

### ISSUE THREAD

**Issue by IrynaPetrash** [inma-no/advertsspec-samples#1]
Hello!
 I have some problems with information. I can't find how to correct errors:
 1.Window.open not called, but is enforced by spec.
 2.Missing clickhandler on banner html element/tag <DIV>.
 Can you help me? Give me some information, please.

 there is my banners http://kopakov.com/ira/ban-3

 Have I to minify pictures for adds?

 I can send you my zip

**Comment by sveisvei** [comment]
The validator requires the whole banner to be clickable at the moment. (@OleSan not sure if this needs review)

**Comment by OleSan** [comment]
As @sveisvei pointed out, the validator checks if the whole banner is clickable. If its OK for your customer that only parts are clickable, you can ignore that error. 

And you don't need to minify images, but we do recommend services like tinypng and tinyjpg to make sure the images leaves a small footprint without a big sacrifice in image quality.
